MovieAndCustomerManager/Models/Rental.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MovieAndCustomerManager.Models
{
    public class Rental
    {
        public int Id { get; set; }

        [Required]
        public Customer Customer { get; set; }

        [Required]
        public Movie Movie { get; set; }

        public DateTime DateRented { get; set; }
        public DateTime? DateReturned { get; set; }
    }
}

MovieAndCustomerManager/Controllers/Api/RentalController.cs
using AutoMapper;
using MovieAndCustomerManager.Dtos;
using MovieAndCustomerManager.Models;
using System;
using System.Linq;
using System.Web.Http;
using System.Data.Entity;
using System.Data.Entity.Validation;

namespace MovieAndCustomerManager.Controllers.Api
{
    public class RentalController : ApiController
    {
        private ApplicationDbContext _context;

        public RentalController()
        {
            _context = new ApplicationDbContext();
        }

        [HttpPost]
        public IHttpActionResult Rental(RentalDto rentalDto)
        {
            //if (rentalDto.MovieIds.Count == 0)
            //    return BadRequest("No movie ID is provided!");

            var customer = _context.Customer.Single(c => c.Id == rentalDto.CustomerId);

            //if (customer == null)
            //    return BadRequest("Customer is not in the database!");

            var movies = _context.Movies.Where(c => rentalDto.MovieIds.Contains(c.Id)).ToList();

            //if (movies.Count != rentalDto.MovieIds.Count)
            //    return BadRequest("One or more movie IDs are invalid!");

            
            foreach(var movie in movies)
            {
                if (movie.NumberOfAvailability == 0)
                    return BadRequest(movie.Name + "is not available.");

                movie.NumberOfAvailability--;

                var rental = new Rental
                {
                    Customer = customer,
                    Movie = movie,
                    DateRented = DateTime.Now
                };

                _context.Rentals.Add(rental);
            }

            _context.SaveChanges();

            return Ok();
        }

        //GET  /api/rental
        [HttpGet]
        public IHttpActionResult GetRentals()
        {
            return Ok(_context.Rentals
                .Include(c => c.Customer)
                .Include(c => c.Movie)
                .ToList()
                .Select(Mapper.Map<Rental, RentalItemDto>));
        }

        //PUT /api/rental/id
        [HttpPut]
        public IHttpActionResult UpdateRental(int id)
        {
            var rentalInDb = _context.Rentals
                .Include(c => c.Customer)
                .Include(c => c.Movie)
                .SingleOrDefault(c => c.Id == id);

            if (rentalInDb == null)
                return NotFound();

            rentalInDb.DateReturned = DateTime.Now;
            rentalInDb.Movie.NumberOfAvailability++;

            _context.SaveChanges();
            return Ok(String.Format("{0:f}", rentalInDb.DateReturned));
        }


    }
}

MovieAndCustomerManager/Controllers/RentalController.cs
using MovieAndCustomerManager.Models;
using System.Web.Mvc;

namespace MovieAndCustomerManager.Controllers
{
    [Authorize]
    public class RentalController : Controller
    {
        // GET: Rental
        public ActionResult New()
        {
            return View();
        }


        //Admin GET:
        public ActionResult Index()
        {
            if (User.IsInRole(Constants.CanManageMovies))
                return View("List");
            return View("New");
        }
    }
}

MovieAndCustomerManager/Views/Rental/List.cshtml
<h1>Rentals</h1>

<table id="rentals" class="table table-hover table-condensed table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Customer</th>
            <th>Movie</th>
            <th>Rental Date</th>
            <th>Return</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

<p>
    @Html.ActionLink("New Rental", "New", "Rental", null, new { @class = "btn btn-primary btn-lg" })
</p>


@section scripts
{
    <script>
        $(document).ready(function () {
            var table = $("#rentals").DataTable({
                ajax: {
                    url: "/api/rental",
                    dataSrc: ""
                },
                columns: [
                    {
                        data: "customerName",
                        render: function (data) {
                            return "<h5>" + data + "</h5>";
                        }
                    },
                    {
                        data: "movieName",
                        render: function (data) {
                            return "<h5>" + data + "</h5>";
                        }
                    },
                    {
                        data: "dateRented",
                        render: function (data) {
                            return "<h5>" + data + "</h5>";
                        }
                    },
                    {
                        data: "id",
                        render: function (data, type, row) {
                            if (!row.dateReturned) {
                                return "<button data-rental-id=" + data + " type='button' class='btn btn-link js-return'>Return</button>";
                            } else {
                                return "<h5>" + row.dateReturned + "</h5>";
                            }
                        }
                    }
                    
                ]
            });

            $("#rentals").on("click", ".js-return", function () {
                var button = $(this);

                bootbox.confirm({
                    message: "Are you sure you want to return this movie?",
                    buttons: {
                        cancel: {
                            label: 'Cancel'
                        },
                        confirm: {
                            label: 'Confirm'
                        }
                    },
                    callback: function (result) {
                        if (result) {
                            $.ajax({
                                url: "/api/rental/" + button.attr("data-rental-id"),
                                method: "PUT",
                                data: {},
                                success: function (data) {
                                    button.replaceWith("<h5>"+ data + "</h5>");
                                }
                            });
                        }
                    }
                });
            });
        });
    </script>
}

MovieAndCustomerManager/Views/Rental/New.cshtml
@{
    ViewBag.Title = "New Rental Form";
}

<h2>New Rental Form</h2>
<form id="newRental">
    <div class="form-group">
        <label>Customer</label>
        <div class="tt-container">
            <input id="customer" name="customer" data-rule-validCustomer="true" required type="text" value="" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <label>Movie</label>
        <div class="tt-container">
            <input id="movie" name="movie" data-rule-validMovies="true"  type="text" value="" class="form-control" />
        </div>
        
    </div>
    <div class="row">
        <div class="col-md-4 col-sm-4">
            <ul id="movies" class="list-group"></ul>
        </div>
    </div>
    
    <button class="btn btn-primary">Submit</button>
</form>

@section scripts
{

    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {

            var vm = {
                movieIds: []
            };

            //var customers = new Bloodhound({
            //    datumTokenizer: Bloodhound.tokenizers.obj.whitespace('Name'),
            //    queryTokenizer: Bloodhound.tokenizers.whitespace,
            //    remote: {
            //        url: '/api/customer?query=%QUERY',
            //        wildcard: '%QUERY'
            //    }
            //});

            var customers = new Bloodhound({
                datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                remote: {
                    url: '/api/customer?query=%QUERY',
                    wildcard: '%QUERY'
                }
            });

            $('#customer').typeahead({
                minLength: 3,
                highlight: true
            }, {
                name: 'customers',
                display: 'name',
                source: customers
            }).on("typeahead:select", function (e, customer) {
                    vm.customerId = customer.id;
                });


            var movies = new Bloodhound({
                datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                remote: {
                    url: '/api/movies?query=%QUERY',
                    wildcard: '%QUERY'
                }
            });

            $('#movie').typeahead({
                minLength: 3,
                highlight: true
            }, {
                    name: 'movies',
                    display: 'name',
                    source: movies
                }).on("typeahead:select", function (e, movie) {
                    $('#movies').append("<li class='list-group-item'>" + movie.name + "</li>");
                    $('#movie').typeahead("val", "");

                    vm.movieIds.push(movie.id);
                });

            $.validator.addMethod("validCustomer", function () {
                return vm.customerId && vm.customerId !== 0;
            }, "Please select a valid customer.");

            $.validator.addMethod("validMovies", function () {
                return vm.movieIds.length > 0;
            }, "Please select at least one movie.");

            var validator = $('#newRental').validate({
                submitHandler: function () {
                    $.ajax({
                        url: "/api/Rental",
                        method: "POST",
                        data: vm
                    }).done(function () {
                        toastr.success("Rentals successfully recorded.");
                        $("#customer").typeahead("val", "");
                        $("#movie").typeahead("val", "");
                        $("#movies").empty();

                        vm = { movieIds: [] }
                        validator.resetForm();
                    }).fail(function () {
                        toastr.error("Something unexpected happens.");
                        });

                    return false;
                }
            });
        });
    </script>
    
    
}